# Generated by Django 4.2.16 on 2024-11-08 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departments_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Majors_name', models.CharField()),
                ('Departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sinh_vien.departments')),
            ],
        ),
        migrations.CreateModel(
            name='sinh_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField()),
                ('birthday', models.DateField()),
                ('Majors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sinh_vien.majors')),
            ],
        ),
    ]
