# Generated by Django 4.2.16 on 2024-11-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sinh_vien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinh_vien',
            name='gioi_tinh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Departments_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='majors',
            name='Majors_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sinh_vien',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
