# Generated by Django 4.2.16 on 2024-09-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='muon_tra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_muon_tra', models.IntegerField()),
                ('ma_sach', models.CharField(max_length=100)),
                ('ngay_muon', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('han_tra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sach', models.IntegerField()),
                ('ten_sach', models.CharField(max_length=100)),
                ('vi_tri', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sinh_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sv', models.IntegerField()),
                ('ngay_muon', models.DateField()),
                ('han_tra', models.DateField()),
                ('so_luong', models.IntegerField()),
            ],
        ),
    ]
