# Generated by Django 4.2.16 on 2024-09-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinh_vien',
            name='so_luong',
        ),
    ]
