# Generated by Django 4.2.16 on 2024-09-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='muon_tra',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='sach',
        ),
        migrations.DeleteModel(
            name='sinh_vien',
        ),
    ]
