# Generated by Django 4.2.16 on 2024-09-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
