# Generated by Django 4.2.16 on 2024-11-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loai_sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_sach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nhom_hoc_phan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhom_hoc_phan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tac_gia', models.CharField(max_length=100)),
                ('nam_xuat_ban', models.IntegerField(null=True)),
                ('loai_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.loai_sach')),
                ('nhom_hoc_phan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.nhom_hoc_phan')),
            ],
        ),
    ]
