# Generated by Django 4.2.16 on 2024-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=20)),
                ('sdt', models.CharField()),
                ('cccd', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='sach',
            name='so_luong',
            field=models.IntegerField(null=True),
        ),
    ]
