# Generated by Django 4.2.16 on 2024-11-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sach', '0002_account_sach_so_luong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='nhom_hoc_phan',
        ),
        migrations.AddField(
            model_name='loai_sach',
            name='nhom_hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.nhom_hoc_phan'),
        ),
    ]
