# Generated by Django 4.2.16 on 2024-11-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sach', '0003_remove_sach_nhom_hoc_phan_loai_sach_nhom_hoc_phan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cccd',
            field=models.CharField(),
        ),
    ]
