# Generated by Django 4.2.16 on 2024-12-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sach', '0004_alter_account_cccd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loai_sach',
            name='nhom_hoc_phan',
        ),
        migrations.RemoveField(
            model_name='sach',
            name='loai_sach',
        ),
        migrations.AddField(
            model_name='nhom_hoc_phan',
            name='Loai_sach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.loai_sach'),
        ),
        migrations.AddField(
            model_name='sach',
            name='Nhom_hoc_phan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.nhom_hoc_phan'),
        ),
        migrations.CreateModel(
            name='Muon_sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('Loai_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.loai_sach')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.account')),
            ],
        ),
    ]
