# Generated by Django 4.2.16 on 2024-12-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_sach', '0005_remove_loai_sach_nhom_hoc_phan_remove_sach_loai_sach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muon_sach',
            name='Loai_sach',
        ),
        migrations.AddField(
            model_name='muon_sach',
            name='sach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.sach'),
        ),
        migrations.CreateModel(
            name='Sach_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.account')),
                ('sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_sach.sach')),
            ],
        ),
    ]
