# Generated by Django 4.2.16 on 2024-11-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=255)),
                ('computer_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_type_name', models.CharField(max_length=20)),
                ('configuration', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
