# Generated by Django 4.2.16 on 2024-11-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_quan_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_quan_game.computer_type'),
        ),
    ]
