# Generated by Django 4.2.16 on 2024-11-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quan_li_quan_game', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='trang_thai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Computer_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_quan_game.account')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='quan_li_quan_game.computer')),
            ],
        ),
    ]
